"""
SDC Constraint Generator
Generates a complete SDC file from user-supplied parameters.
"""

from dataclasses import dataclass, field
from typing import List, Optional
from datetime import date


@dataclass
class ClockDef:
    name: str
    clk_type: str = "primary"       # "primary" | "generated" | "virtual"
    port: str = ""
    period: float = 5.0
    uncertainty: float = 0.15
    duty_cycle: Optional[float] = None
    # Generated clock switches
    master_port: str = ""
    divide_by: int = 2
    multiply_by: Optional[int] = None
    edge_shift: str = ""
    invert: bool = False
    preinvert: bool = False
    combinational: bool = False
    add_flag: bool = False


@dataclass
class FalsePath:
    from_obj: str
    to_obj: str


@dataclass
class MultiCyclePath:
    from_cell: str
    to_cell: str
    cycles: int = 2


@dataclass
class HalfCyclePath:
    clock: str
    direction: str = "rise_to_fall"   # "rise_to_fall" | "fall_to_rise" | "both"


@dataclass
class CaseAnalysisEntry:
    target: str
    value: str = "0"    # 0 | 1 | rising | falling
    obj_type: str = "port"   # "port" | "pin"


@dataclass
class DisableArc:
    cell: str
    from_pin: str
    to_pin: str


@dataclass
class PathGroup:
    name: str
    from_obj: str = ""
    to_obj: str = ""
    weight: float = 1.0


@dataclass
class SDCParams:
    design_name: str = "MY_DESIGN"
    sdc_version: str = "2.2"

    # Units
    add_units: bool = True
    time_unit: str = "ns"
    cap_unit: str = "pF"
    res_unit: str = "kOhm"

    # Clocks
    clocks: List[ClockDef] = field(default_factory=lambda: [
        ClockDef(name="clk_core", port="clk", period=5.0, uncertainty=0.15)
    ])
    add_clk_jitter: bool = False
    clk_jitter_val: float = 0.05
    add_clk_transition: bool = False
    clk_transition_val: float = 0.1
    add_clk_gating: bool = False
    clk_gate_setup: float = 0.5
    clk_gate_hold: float = 0.2
    add_latency: bool = False
    latency_val: float = 0.5
    add_propagated: bool = False

    # I/O
    in_delay_max: float = 1.2
    in_delay_min: float = 0.4
    out_delay_max: float = 1.5
    out_delay_min: float = 0.5
    add_drive_cell: bool = True
    drive_cell_name: str = "BUF_X4"
    add_input_transition: bool = False
    input_transition_val: float = 0.1
    add_load: bool = True
    load_val: float = 0.05

    # Design rules
    max_fanout: int = 20
    max_transition: float = 0.2
    max_cap: float = 0.1
    min_cap: Optional[float] = None
    max_area: Optional[float] = None

    # Operating conditions
    add_oper_cond: bool = False
    oper_cond_name: str = "WORST"

    # Timing derate
    add_derate: bool = False
    derate_cell_late: float = 0.92
    derate_cell_early: float = 1.08
    derate_net_late: float = 1.0
    derate_net_early: float = 1.0

    # Ideal / DFT
    add_ideal_rst: bool = True
    rst_port: str = "rst_n"
    add_scan: bool = False
    scan_port: str = "scan_en"
    add_min_pulse: bool = False
    min_pulse_val: float = 0.5
    case_entries: List[CaseAnalysisEntry] = field(default_factory=list)

    # Disable timing arcs
    disable_arcs: List[DisableArc] = field(default_factory=list)

    # Path groups
    add_group_path: bool = False
    path_groups: List[PathGroup] = field(default_factory=lambda: [
        PathGroup(name="reg2reg")
    ])

    # Wire load
    add_wire_load: bool = False
    wire_load_mode: str = "top"
    wire_load_model: str = ""

    # Timing exceptions
    false_paths: List[FalsePath] = field(default_factory=list)
    mc_paths: List[MultiCyclePath] = field(default_factory=list)
    half_paths: List[HalfCyclePath] = field(default_factory=list)

    # Power
    add_power: bool = False
    max_dyn_power: float = 100.0
    max_leak_power: float = 10.0

    # Dont-use
    dont_use: List[str] = field(default_factory=list)


def generate_sdc(p: SDCParams) -> str:
    L = []
    today = date.today().isoformat()

    primary_clocks = [c for c in p.clocks if c.clk_type == "primary" and c.name]
    p_clk = primary_clocks[0].name if primary_clocks else "clk_core"
    clk_ports = " ".join(c.port for c in p.clocks if c.port and c.clk_type != "virtual")
    exclude_ports = " ".join(filter(None, [clk_ports, p.rst_port if p.add_ideal_rst else ""]))

    L.append(f"set sdc_version {p.sdc_version}")
    if p.add_units:
        L.append(f"set_units -time {p.time_unit} -capacitance {p.cap_unit} -resistance {p.res_unit}")
    L.append(f"# {p.design_name}.sdc  —  generated by SDC Tools  {today}")
    L.append(f"# NOTE: Review all values before using in synthesis.")
    L.append("")

    # ── Clock definitions ───────────────────────────────────────────────────
    L.append("# ── Clock definitions ───────────────────────────────────────────")
    for c in p.clocks:
        if not c.name:
            continue
        if c.clk_type == "virtual":
            L.append("# Virtual clock — no physical port source")
            L.append(f"create_clock -name {c.name} -period {c.period:.3f}")
        elif c.clk_type == "primary":
            if not c.port:
                continue
            wave = ""
            if c.duty_cycle is not None:
                high_time = round(c.period * c.duty_cycle / 100, 3)
                wave = f" -waveform {{0 {high_time}}}"
            L.append(f"create_clock -name {c.name} -period {c.period:.3f}{wave} [get_ports {c.port}]")
        else:  # generated
            if not c.port or not c.master_port:
                continue
            L.append(f"create_generated_clock -name {c.name} \\")
            L.append(f"  -source [get_ports {c.master_port}] \\")
            if c.multiply_by:
                L.append(f"  -multiply_by {c.multiply_by} \\")
            else:
                L.append(f"  -divide_by {c.divide_by} \\")
            if c.duty_cycle is not None:
                L.append(f"  -duty_cycle {c.duty_cycle} \\")
            if c.edge_shift:
                L.append(f"  -edge_shift {{{c.edge_shift}}} \\")
            if c.invert:
                L.append("  -invert \\")
            if c.preinvert:
                L.append("  -preinvert \\")
            if c.combinational:
                L.append("  -combinational \\")
            if c.add_flag:
                L.append("  -add \\")
            if len(primary_clocks) > 1:
                L.append(f"  -master_clock {c.master_port} \\")
            L.append(f"  [get_ports {c.port}]")
    L.append("")

    # ── Clock attributes ────────────────────────────────────────────────────
    L.append("# ── Clock attributes ────────────────────────────────────────────")
    for c in p.clocks:
        if not c.name:
            continue
        hold_unc = round(c.uncertainty * 0.5, 3)
        L.append(f"set_clock_uncertainty -setup {c.uncertainty} [get_clocks {c.name}]")
        L.append(f"set_clock_uncertainty -hold  {hold_unc} [get_clocks {c.name}]")
    if p.add_latency:
        all_names = " ".join(c.name for c in p.clocks if c.name)
        L.append(f"set_clock_latency -source {p.latency_val} [get_clocks {{{all_names}}}]")
    if p.add_propagated and primary_clocks:
        names = " ".join(c.name for c in primary_clocks)
        L.append(f"set_propagated_clock [get_clocks {{{names}}}]")
    if p.add_clk_transition:
        L.append(f"set_clock_transition {p.clk_transition_val} [all_clocks]")
    if p.add_clk_jitter:
        all_names = " ".join(c.name for c in p.clocks if c.name)
        L.append(f"set_clock_jitter -clock [get_clocks {{{all_names}}}] -cycle {p.clk_jitter_val}")
    if p.add_clk_gating:
        L.append(f"set_clock_gating_check -setup {p.clk_gate_setup} -hold {p.clk_gate_hold}")
    if len(primary_clocks) > 1:
        L.append("")
        L.append("# ── CDC — asynchronous clock groups ────────────────────────────")
        L.append("set_clock_groups -asynchronous \\")
        for i, c in enumerate(primary_clocks):
            cont = " \\" if i < len(primary_clocks) - 1 else ""
            L.append(f"  -group [get_clocks {c.name}]{cont}")
    L.append("")

    # ── I/O constraints ─────────────────────────────────────────────────────
    L.append("# ── I/O constraints ─────────────────────────────────────────────")
    if p.in_delay_max:
        L.append(f"set_input_delay -max {p.in_delay_max} -clock {p_clk} \\")
        L.append(f"  [remove_from_collection [all_inputs] [get_ports {{{exclude_ports}}}]]")
    if p.in_delay_min:
        L.append(f"set_input_delay -min {p.in_delay_min} -clock {p_clk} \\")
        L.append(f"  [remove_from_collection [all_inputs] [get_ports {{{exclude_ports}}}]]")
    if p.out_delay_max:
        L.append(f"set_output_delay -max {p.out_delay_max} -clock {p_clk} [all_outputs]")
    if p.out_delay_min:
        L.append(f"set_output_delay -min {p.out_delay_min} -clock {p_clk} [all_outputs]")
    if p.add_drive_cell and p.drive_cell_name and not p.add_input_transition:
        L.append(f"set_driving_cell -lib_cell {p.drive_cell_name} -pin Z \\")
        L.append(f"  [remove_from_collection [all_inputs] [get_ports {{{clk_ports}}}]]")
    if p.add_input_transition and not p.add_drive_cell:
        L.append(f"set_input_transition {p.input_transition_val} \\")
        L.append(f"  [remove_from_collection [all_inputs] [get_ports {{{clk_ports}}}]]")
    if p.add_load:
        L.append(f"set_load {p.load_val} [all_outputs]")
    L.append("")

    # ── Design rule constraints ──────────────────────────────────────────────
    L.append("# ── Design rule constraints ─────────────────────────────────────")
    if p.max_fanout:
        L.append(f"set_max_fanout     {p.max_fanout} [all_inputs]")
    if p.max_transition:
        L.append(f"set_max_transition {p.max_transition} [all_nets]")
    if p.max_cap:
        L.append(f"set_max_capacitance {p.max_cap} [all_nets]")
    if p.min_cap:
        L.append(f"set_min_capacitance {p.min_cap} [all_nets]")
    if p.max_area is not None:
        L.append(f"set_max_area {p.max_area}")
    L.append("")

    if p.add_oper_cond:
        L.append("# ── Operating conditions ────────────────────────────────────────")
        L.append(f"set_operating_conditions -max {p.oper_cond_name}")
        L.append("")

    if p.add_derate:
        L.append("# ── Timing derate (AOCV) ────────────────────────────────────────")
        L.append(f"set_timing_derate -late  -cell_delay {p.derate_cell_late}  [all_nets]")
        L.append(f"set_timing_derate -early -cell_delay {p.derate_cell_early} [all_nets]")
        L.append(f"set_timing_derate -late  -net_delay  {p.derate_net_late}   [all_nets]")
        L.append(f"set_timing_derate -early -net_delay  {p.derate_net_early}  [all_nets]")
        L.append("")

    if p.add_ideal_rst and p.rst_port:
        L.append("# ── Ideal networks ──────────────────────────────────────────────")
        L.append(f"set_ideal_network [get_ports {p.rst_port}]")
        L.append(f"set_false_path -from [get_ports {p.rst_port}]")
        L.append("")

    if p.add_scan and p.scan_port:
        L.append("# ── Scan / DFT ──────────────────────────────────────────────────")
        L.append(f"set_case_analysis 0 [get_ports {p.scan_port}]")
        L.append(f"set_ideal_network [get_ports {p.scan_port}]")
        L.append("")

    if p.add_min_pulse:
        L.append(f"set_min_pulse_width -low  {p.min_pulse_val} [all_clocks]")
        L.append(f"set_min_pulse_width -high {p.min_pulse_val} [all_clocks]")
        L.append("")

    valid_ca = [e for e in p.case_entries if e.target and e.value]
    if valid_ca:
        L.append("# ── Case analysis entries ───────────────────────────────────────")
        for e in valid_ca:
            obj = f"[get_pins {e.target}]" if e.obj_type == "pin" else f"[get_ports {e.target}]"
            L.append(f"set_case_analysis {e.value} {obj}")
        L.append("")

    valid_da = [d for d in p.disable_arcs if d.cell and d.from_pin and d.to_pin]
    if valid_da:
        L.append("# ── Disable timing arcs ─────────────────────────────────────────")
        for d in valid_da:
            L.append(f"set_disable_timing -from {d.from_pin} -to {d.to_pin} [get_cells {d.cell}]")
        L.append("")

    if p.add_group_path:
        valid_gp = [g for g in p.path_groups if g.name]
        if valid_gp:
            L.append("# ── Path groups ─────────────────────────────────────────────────")
            for g in valid_gp:
                cmd = f"group_path -name {g.name}"
                if g.from_obj:
                    cmd += f" -from [get_ports {g.from_obj}]"
                if g.to_obj:
                    cmd += f" -to [get_ports {g.to_obj}]"
                if g.weight != 1.0:
                    cmd += f" -weight {g.weight}"
                L.append(cmd)
            L.append("")

    if p.add_wire_load:
        L.append("# ── Wire load ───────────────────────────────────────────────────")
        L.append(f"set_wire_load_mode {p.wire_load_mode}")
        if p.wire_load_model:
            L.append(f"set_wire_load_model -name {p.wire_load_model} [current_design]")
        L.append("")

    valid_fp = [f for f in p.false_paths if f.from_obj and f.to_obj]
    if valid_fp:
        L.append("# ── False paths ─────────────────────────────────────────────────")
        for fp in valid_fp:
            L.append(f"set_false_path -from [get_ports {fp.from_obj}] -to [get_ports {fp.to_obj}]")
        L.append("")

    valid_mc = [m for m in p.mc_paths if m.from_cell and m.to_cell and m.cycles > 0]
    if valid_mc:
        L.append("# ── Multicycle paths ────────────────────────────────────────────")
        for mc in valid_mc:
            L.append(f"set_multicycle_path -setup {mc.cycles} -from [get_cells {mc.from_cell}] -to [get_cells {mc.to_cell}]")
            L.append(f"set_multicycle_path -hold  {mc.cycles - 1} -from [get_cells {mc.from_cell}] -to [get_cells {mc.to_cell}]")
        L.append("")

    valid_hp = [h for h in p.half_paths if h.clock]
    if valid_hp:
        L.append("# ── Half-cycle paths ────────────────────────────────────────────")
        L.append("# Half-cycle: launch and capture on opposite clock edges (budget = period/2)")
        for h in valid_hp:
            ref = f"[get_clocks {h.clock}]"
            if h.direction in ("rise_to_fall", "both"):
                L.append(f"set_multicycle_path -setup 1 -end -rise_to {ref}")
                L.append(f"set_multicycle_path -hold  0 -end -rise_to {ref}")
            if h.direction in ("fall_to_rise", "both"):
                L.append(f"set_multicycle_path -setup 1 -end -fall_to {ref}")
                L.append(f"set_multicycle_path -hold  0 -end -fall_to {ref}")
        L.append("")

    if p.add_power:
        L.append("# ── Power constraints ───────────────────────────────────────────")
        L.append(f"set_max_dynamic_power {p.max_dyn_power} mW")
        L.append(f"set_max_leakage_power {p.max_leak_power} uW")
        L.append("")

    valid_du = [d for d in p.dont_use if d]
    if valid_du:
        L.append("# ── Dont-use cells ──────────────────────────────────────────────")
        for cell in valid_du:
            L.append(f"set_dont_use [get_lib_cells */{cell}]")

    return "\n".join(L)
